
views.py > index
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Program Files\Python\Python310\lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner    
    response = get_response(request)
  File "C:\Program Files\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\OK\source\repos\Repository4_python\django_test\test_project1\test_project1\view_modules\views.py", line 7, in index
    return render(request, 'index.html')
  File "C:\Program Files\Python\Python310\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Program Files\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string 
    template = get_template(template_name, using=using)
  File "C:\Program Files\Python\Python310\lib\site-packages\django\template\loader.py", line 15, in get_template     
    return engine.get_template(template_name)
  File "C:\Program Files\Python\Python310\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Program Files\Python\Python310\lib\site-packages\django\template\engine.py", line 177, in get_template    
    template, origin = self.find_template(template_name)
  File "C:\Program Files\Python\Python310\lib\site-packages\django\template\engine.py", line 159, in find_template   
    template = loader.get_template(name, skip=skip)
  File "C:\Program Files\Python\Python310\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Program Files\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Program Files\Python\Python310\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Program Files\Python\Python310\lib\site-packages\django\template\base.py", line 196, in compile_nodelist  
    return parser.parse()
  File "C:\Program Files\Python\Python310\lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Program Files\Python\Python310\lib\site-packages\django\template\base.py", line 565, in invalid_block_tag 
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'static'. Did you forget to register or 
load this tag?
[10/Aug/2025 13:57:28] "GET / HTTP/1.1" 500 139872
